mon_projet:
  target: dev
  outputs:
    dev:
      type: mysql
      server: 127.0.0.1
      port: 3306
      user: root
      password: '...'
      schema: dbt_demo  # Nom de ta base de données dans MySQL
      database: dbt_demo  # <- doit être le même que `schema`
